# Generated by Django 3.2.7 on 2022-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artiste',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='artwork',
            field=models.ImageField(blank=True, default=True, upload_to='staticfiles/'),
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.FileField(default=True, upload_to='mediafiles/'),
        ),
    ]
