# Generated by Django 3.2.7 on 2022-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artiste',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
